chore(deps): update deps and apollo server to v4
notiz-dev/nestjs-prisma-starter pull request #476
Opened 2023-03-11 20:50 UTC by luluhoc

2023-03-11 20:50 UTC, luluhoc commented
@marcjulian

2023-03-16 09:42 UTC, marcjulian requested changes
Thanks looks good, but I will stick to npm and will readd package-lock.json. But we can add info for yarn to the readme.

Can you check if the Graphql Playground still works or if we can enable GraphiQL as the Playground is discontinued.

2023-03-16 09:42 UTC, marcjulian commented on src/gql-config.service.ts
>        playground: graphqlConfig.playgroundEnabled,
Is the playground still supported? I receive the following error when opening [http://localhost:3000/grapqhl](http://localhost:3000/grapqhl)

```
{"statusCode":404,"message":"Cannot GET /grapqhl","error":"Not Found"}
```

2023-03-16 09:42 UTC, marcjulian commented on README.md
> +yarn add -g @nestjs/cli
```suggestion
# npm
npm i -g @nestjs/cli
# yarn
yarn add -g @nestjs/cli
```

2023-03-16 09:42 UTC, marcjulian commented on README.md
> +yarn install
```suggestion
# npm
npm install
# yarn
yarn install
```

2023-03-19 23:45 UTC, luluhoc commented on src/gql-config.service.ts
>        playground: graphqlConfig.playgroundEnabled,
Yes, it is still supported, it's your url, you have a typo.

2023-03-19 23:46 UTC, luluhoc commented
@marcjulian all resolved

2023-03-27 08:40 UTC, marcjulian commented on src/gql-config.service.ts
>        playground: graphqlConfig.playgroundEnabled,
True, sorry about that.

2023-03-27 08:40 UTC, marcjulian approved these changes
LGTM!

2023-03-27 08:41 UTC, merged